insert into EMPLOYEE (ID, NAME, SURNAME, POSITION, BIRTHDAY, DAILY_WAGE)
values (1, 'Adam', 'Reynolds', 'SALESMAN', '1991-10-01', 250);

insert into EMPLOYEE (ID, NAME, SURNAME, POSITION, BIRTHDAY, DAILY_WAGE)
values (2, 'Susan', 'Kaminsky', 'SALES_LEADER', '1990-02-01', 450);